// Global data: the list of files in assets/, read at build time. Eleventy runs
// this on every build (locally and in CI), so the gallery always reflects what
// is actually in the folder. Alt text and the base URL are merged in the
// template from the alts/site data files (generated by the conversion pipeline).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const assetsDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "assets");
const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".bmp"]);

export default function () {
  if (!fs.existsSync(assetsDir)) return [];
  return fs
    .readdirSync(assetsDir)
    .filter((name) => !name.startsWith("."))
    .sort()
    .map((name) => {
      const ext = path.extname(name).toLowerCase();
      return { name, ext: ext.replace(/^\./, ""), isImage: IMAGE_EXTS.has(ext) };
    });
}
